chapter 6.3까지 실습
ham-study/jwp pull request #12
Opened 2023-03-26 03:57 UTC by seung-hun-h

2023-03-29 12:59 UTC, rlatls1997 requested changes
PR 확인했습니다~

2023-03-29 12:59 UTC, rlatls1997 commented on src/main/java/next/web/UpdateUserServlet.java
> +	}
제가 리뷰받았던 것과 동일한 부분인데, 현재 코드에선 다른 유저도 수정할 수 있어서 세션 사용자 검증이 필요한 것 같습니다

2023-03-29 12:59 UTC, rlatls1997 commented on src/main/webapp/components/footer.jsp
파일 나누는건 사람마다 다르긴 한데, header, footer를 말하면 화면 레이아웃에서 `<header>`, `<footer>` 시멘틱태그로 들어가는 영역일거라고 생각돼서 레이아웃이 아닌 스크립트 태그와 `<head>`태그로 나뉜게 좀 어색하게 느껴졌습니다.

개인적인 생각이라 footer.jsp, header.jsp는 굳이 수정안해도 될 것 같습니다.

2023-03-31 01:13 UTC, seung-hun-h commented
@rlatls1997 리뷰 반영했습니다!

2023-03-31 01:50 UTC, rlatls1997 approved these changes

2023-03-31 08:49 UTC, merged