7.2 DAO 리팩토링 실습
ham-study/jwp pull request #16
Opened 2023-04-19 17:06 UTC by rlatls1997

2023-04-22 09:28 UTC, seung-hun-h commented on src/main/java/next/controller/CreateUserController.java
> +import java.sql.SQLException;
SQLException은 왜 추가됐나요??

2023-04-22 09:29 UTC, seung-hun-h commented on src/main/java/next/jdbctemplate/JdbcTemplate.java
> +	}
퍼블릭 인터페이스에서는 SQLException을 제거하는게 좋을 것 같네요

2023-04-22 09:30 UTC, seung-hun-h commented on src/main/java/next/jdbctemplate/JdbcTemplate.java
> +			 PreparedStatement preparedStatement = connection.prepareStatement(sql)
이 부분도 계속 중복되는 것 같은데, 중복되는 코드를 제거할 수는 없을까요??

2023-04-22 09:31 UTC, seung-hun-h requested changes
리뷰 남겼습니다~

2023-04-25 14:10 UTC, rlatls1997 commented on src/main/java/next/controller/CreateUserController.java
> +import java.sql.SQLException;
미처 제거하지 못했네요; 제거하겠습니다.

2023-04-25 14:20 UTC, rlatls1997 commented on src/main/java/next/jdbctemplate/JdbcTemplate.java
> +			 PreparedStatement preparedStatement = connection.prepareStatement(sql)
try문 resource절은 따로 분리할 수 없을 것 같아서요. 
내부 로직을 파라미터로 빼자니 resultSet있고 없고의 차이도 그렇고 당장은 어떻게 할지 생각이 안떠오르네요.
고민해보겠습니다

2023-04-25 14:34 UTC, rlatls1997 commented
> 리뷰 남겼습니다~
> 
> 다른 컨트롤러는 새로 작성한 `UserDao`를 적용하지 않았나요??

예제 이후 테스트코드까지만 패스하도록 작업했습니다.

2023-04-25 22:28 UTC, seung-hun-h approved these changes

2023-04-26 11:21 UTC, merged