step7
ham-study/jwp pull request #22
Opened 2023-05-28 13:59 UTC by rlatls1997

2023-05-29 02:15 UTC, seung-hun-h requested changes

2023-05-29 02:15 UTC, seung-hun-h commented on src/main/java/next/service/qna/QnaService.java
> +	}
`userName`이 필요한 파라미터인가요?
요구사항을 보면 질문의 작성자와 답변의 작성자만 비교하면 될 것 같아서요.

요구 사항은 '질문자와 답변자가 다른 답변이 하나라도 있으면 질문을 제거할 수 없다'인데, 코드상 파라미터로 전달받은 `useName`이 아닌 다른 답변이 있는 경우에 질문이 제거될  수 것 같네요,

2023-05-31 09:45 UTC, rlatls1997 commented on src/main/java/next/service/qna/QnaService.java
> +	}
지금 책이 없어서요. 요구사항에 있었는지는 기억이 안나는데
질문자와 사용자가 다른 경우를 검사하기 위해 userName 파라미터를 전달했습니다.

2023-06-01 13:12 UTC, seung-hun-h commented on src/main/java/next/service/qna/QnaService.java
> +	}
요구 사항 중 `질문자와 답변자가 다른 답변이 하나라도 있으면 질문을 제거할 수 없다`라고 되어있어요.
위 코드는 질문자와 사용자가 다른 경우만 고려하고 있고, 질문자와 답변자가 다른 답변을 찾는 로직이 없어서요

2023-06-01 13:51 UTC, rlatls1997 commented on src/main/java/next/service/qna/QnaService.java
> +	}
25라인 countOfAnswersByQuestionIdAndWriter() 메서드에 userName을 전달하고 있습니다.
이 메서드에선 특정 질문 중 작성자가 userName인 답변의 개수를 반환하는데 이 값을 검사하여 해당 요구사항을 구현했어요

2023-06-01 13:53 UTC, seung-hun-h commented on src/main/java/next/service/qna/QnaService.java
> +	}
아 그렇군요! 
머지해도 좋을 것 같습니다

2023-06-01 14:03 UTC, merged