chapter2
ham-study/jwp pull request #3
Opened 2023-01-28 15:46 UTC by rlatls1997

2023-01-31 10:48 UTC, seung-hun-h requested changes
리뷰 남겼습니다~

2023-01-31 10:48 UTC, seung-hun-h commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	private static final Pattern CUSTOM_DELIMITER_REGEX = Pattern.compile("^\\/\\/(?<delimiter>.)\\n(?<expression>.*)");
이런식으로 이름을 줄 수 있는 건 처음 알았네요
이름이 정규식이랑 메서드에 분산되어 있어서 상수로 관리하면 더 좋을 것 같습니다

2023-01-31 10:48 UTC, seung-hun-h commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	int add(String text) {
접근 제어자가 default로 설정되어 있는데 이유가 있나요?

2023-01-31 10:48 UTC, seung-hun-h commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	}
Pattern 객체를 또 생성해서 넘겨 줄 필요가 있었을까 싶네요
`text.split()`에 정규 표현식을 넘길 수 있어서 String text, String delimiter 로 처리할 수 있을 것 같아서요

2023-01-31 10:48 UTC, seung-hun-h commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +		String text = "1,2:3";
비슷한 부분이 반복되고 있어서 `@ParameterizedTest`를 사용하면 좋을 것 같아요

2023-01-31 10:48 UTC, seung-hun-h commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +			String text = "1,-2:3";
음수랑 잘못된 기본 구분자에 대한 테스트를 하고 있는 것 같아서 뭔가 한 번에 두 가지 테스트를 하고 있는 것 같네요.

2023-01-31 16:04 UTC, rlatls1997 commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	private static final Pattern CUSTOM_DELIMITER_REGEX = Pattern.compile("^\\/\\/(?<delimiter>.)\\n(?<expression>.*)");
이름 분리하는게 낫겠네요 동의합니다.

2023-01-31 16:04 UTC, rlatls1997 commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	int add(String text) {
이건 별 생각없었네요. 56쪽 메서드 구조 짜놓고 출발했습니다.

2023-01-31 16:04 UTC, rlatls1997 commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	}
이건.. default delimiter에 해당하는 수식 계산 메서드 addSplitNumbers를 짜놓고 시작했는데 이 메서드에 끼워맞추다보니 불필요한 객체생성을 한 것 같네요.

객체생성 없애고 공통으로 사용할 수 있는 메서드를 만들어봐야겠습니다.

2023-01-31 16:04 UTC, rlatls1997 commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +			String text = "1,-2:3";
이 부분은 이해가 잘 안되네요. 기본구분자는 ,와 : 둘 다 허용인데 둘 다 동시에 사용하면 헷갈릴 수 있다는건가요?

2023-01-31 16:49 UTC, rlatls1997 commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	}
String.split 내부 구현을 보니.. 결국에는 Pattern객체 생성해서 Pattern.split메서드로 문자열을 쪼개는데 기본delimiter 케이스의 경우와 동일한 메서드로 처리할 겸 Pattern객체를 생성하는것도 나쁘지 않다고 생각해서 놔두게 되었습니다

2023-02-01 01:50 UTC, seung-hun-h commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +			String text = "1,-2:3";
기본 구분자가 콜론(:)이 아닌 세미 콜론(;)으로 알고 있는데 아닌가요?

2023-02-01 07:06 UTC, rlatls1997 commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +			String text = "1,-2:3";
p.55 맨 윗문장 보고 했네요. 여기보고 기본구분자를 , 또는 :로 사용했습니다

2023-02-01 08:52 UTC, seung-hun-h commented on src/test/java/org/hamstudy/chap02/StringCalculatorTest.java
> +			String text = "1,-2:3";
아 제가 잘못알고 있었네요;;

2023-02-01 08:53 UTC, seung-hun-h commented on src/main/java/org/hamstudy/chap02/StringCalculator.java
> +	}
> String.split 내부 구현을 보니.. 결국에는 Pattern객체 생성해서 Pattern.split메서드로 문자열을 쪼개는데 기본delimiter 케이스의 경우와 동일한 메서드로 처리할 겸 Pattern객체를 생성하는것도 나쁘지 않다고 생각해서 놔두게 되었습니다

흠 그렇군요 이것도 새롭게 알아가네요

2023-02-01 08:54 UTC, seung-hun-h approved these changes
수고 하셨습니다 머지 해도 좋을 것 같네요

2023-02-01 09:02 UTC, merged