chapter3
ham-study/jwp pull request #8
Opened 2023-02-19 14:55 UTC by rlatls1997

2023-02-24 08:43 UTC, seung-hun-h requested changes
리뷰 남겼습니다. 확인해주세요

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/user/UserProcessor.java
> +	}
메서드 네이밍이 모호한 것 같습니다.
User가 없다고 Invalid한 것은 아니라고 생각하거든요. `exist`같은 prefix를 사용하는 것이 좋아보이네요

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +		if (queryStringStartIndex == -1) {
인덱스가 -1이면 존재하지 않는 것을 나타내는데 메서드로 분리하면 의미가 명확해질 것 같습니다

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +			}
로그인에 실패했을 때 쿠키를 보내 줄 필요가 있을까요?
실패한 응답을 따로 내려주는 것이 맞아보이는데 어떻게 생각하시나요?>

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +	}
이런 로직은 HttpRequestUtils에 넣어줘도 좋겠네요

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +	}
뎁스가 너무 깊습니다. 분리할 필요가 있을 것 같아요.
`:`는 헤더에서 공통으로 사용하고 있는 구분자이므로 상수로 분리해도 좋을 것 같습니다.

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +	private void response302HeaderWithLoginedCookie(DataOutputStream dos, int lengthOfBodyContent, boolean isLoginSuccess, String location) {
이 메서드도 일반화 할 수 있어 보입니다.
```suggestion
	private void response302Header(DataOutputStream dos, int lengthOfBodyContent, Map<String, List<String>> headers, String location) {
```

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +	public Map<String, String> getHttpRequestBodyMap(BufferedReader br, List<String> httpRequestContents) throws IOException {
이건 왜 public 인가요?

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/webserver/RequestHandler.java
> +				case "/user/list" -> getUserList(httpCookie, dos);
메서드에 대한 확인은 필요없을까요?
동일한 URI로 GET이나 POST 요청이 간다면 구분할 수 없을 것 같아서요

2023-02-24 08:43 UTC, seung-hun-h commented on src/main/java/user/UserProcessor.java
> +public class UserProcessor {
UserProcessor는 유틸 클래스인가요?
```suggestion
public final class UserProcessor {
	private UserProcessor() { }
```

그렇다면 상속과 인스턴스 생성을 막아줄 필요가 있어 보이네요

2023-02-25 11:02 UTC, rlatls1997 commented on src/main/java/user/UserProcessor.java
> +	}
user존재여부 검사, password체크를 분리하던지 메서드이름을 변경해봐야겠네요

2023-02-25 11:02 UTC, rlatls1997 commented on src/main/java/webserver/RequestHandler.java
> +	public Map<String, String> getHttpRequestBodyMap(BufferedReader br, List<String> httpRequestContents) throws IOException {
메서드를 여기저기 옮기다가 놓쳤네요. 수종하겠습니다.

2023-02-25 11:02 UTC, rlatls1997 commented on src/main/java/webserver/RequestHandler.java
> +		if (queryStringStartIndex == -1) {
네 메서드로 분리하는게 훨씬 명확하겠네요

2023-02-25 11:02 UTC, rlatls1997 commented on src/main/java/webserver/RequestHandler.java
> +	private void response302HeaderWithLoginedCookie(DataOutputStream dos, int lengthOfBodyContent, boolean isLoginSuccess, String location) {
넵 수정해보겠습니다

2023-02-25 11:02 UTC, rlatls1997 commented on src/main/java/webserver/RequestHandler.java
> +			}
이부분은 요구사항 5번 스펙이라서 실패시에도 쿠기값을 내려주도록 했습니다.

2023-02-26 03:31 UTC, seung-hun-h commented
- '/user' 하위 path

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/60502370/221390741-66a1731c-d5b9-4663-a2bf-3397dcd68c5f.png">
---
- '/' root path

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/60502370/221390745-1829a325-3dc7-4bb5-a55c-fcbba9728e18.png">

위 두 이미지를 보면 '/user' 하위 path에서 생성된 쿠키가 root에서는 공유되지 않는다는 거 알고 있으셨나요?
저번에도 이래서 로직 오류인 줄 알았는데 쿠키가 원래 그렇다네요. 다른 path에서 쿠키를 공유하기 위해서는 path를 추가해주면 된다고 합니다

- https://stackoverflow.com/questions/945862/retrieve-a-cookie-from-a-different-path

2023-02-26 16:13 UTC, rlatls1997 commented
> * '/user' 하위 path
> 
> <img alt="image" width="1136" src="https://user-images.githubusercontent.com/60502370/221390741-66a1731c-d5b9-4663-a2bf-3397dcd68c5f.png">
> 
> --- - '/' root path
> <img alt="image" width="1177" src="https://user-images.githubusercontent.com/60502370/221390745-1829a325-3dc7-4bb5-a55c-fcbba9728e18.png">
> 
> 위 두 이미지를 보면 '/user' 하위 path에서 생성된 쿠키가 root에서는 공유되지 않는다는 거 알고 있으셨나요? 저번에도 이래서 로직 오류인 줄 알았는데 쿠키가 원래 그렇다네요. 다른 path에서 쿠키를 공유하기 위해서는 path를 추가해주면 된다고 합니다
> 
> * https://stackoverflow.com/questions/945862/retrieve-a-cookie-from-a-different-path

몰랐던 내용이네요; 공유 감사합니다.

2023-03-01 11:10 UTC, seung-hun-h approved these changes
수정한거 리뷰 남겼습니다. 반영은 다음 PR에 해주세요

2023-03-01 11:10 UTC, seung-hun-h commented on src/main/java/webserver/RequestEntity.java
> +		}
`queryStrings`를 먼저 초기화해도 좋을 것 같네요

```suggestion
String path;
Map<String, String> queryStrings = new HashMap<>();

if (queryStringStartIndex == -1) {
	path = requestUrl;
	queryStrings = Collections.emptyMap();
} else {
	path = requestUrl.substring(0, queryStringStartIndex);
	String wholeQueryString = requestUrl.substring(queryStringStartIndex);
	queryStrings.putAll(HttpRequestUtils.parseQueryString(wholeQueryString));
}
```

2023-03-01 11:10 UTC, seung-hun-h commented on src/main/java/webserver/ResponseEntity.java
> +			.reasonPhrase("OK");
statusCode, reasonPhrase는 항상 묶여서 변경되지 않아 Enum으로 관리하는 것도 좋아보입니다

2023-03-01 11:10 UTC, seung-hun-h commented on src/main/java/webserver/ResponseEntity.java
> +		}
지금도 좋지만 Depth가 2여서
```suggestion
		StringBuilder sb = new StringBuilder();
		
		for(Map.Entry<String, String> entrySet : cookies.entrySet()) {
			sb.append(entrySet.getKey() + "=" + entrySet.getValue() + ";");
		}
		
		if (sb.isEmpty()) {
			return;
		}
		
		Set<String> cookieKeys = cookies.keySet();
		dataOutputStream.writeBytes("Set-Cookie: ");
		dataOutputStream.writeBytes(sb.toString());
		dataOutputStream.writeBytes("path=/;");
		dataOutputStream.writeBytes("\r\n");
```

요렇게 작성하면 더 깔끔할 것 같아요

2023-03-01 11:10 UTC, seung-hun-h commented on src/main/java/webserver/ResponseEntity.java
> +	}
빌더 패턴을 적용하니 가독성이 좋아진 것 같네요.
그런데 인터페이스를 정의할 필요가 있었나요?? 내부에서만 사용하는 것 같아 인터페이스까지는 필요 없을 것 같아서요

2023-03-01 11:39 UTC, rlatls1997 commented on src/main/java/webserver/RequestEntity.java
> +		}
queryStrings의 경우 굳이 분기처리를 하지 않아도 됐었네요.

2023-03-01 11:39 UTC, rlatls1997 commented on src/main/java/webserver/ResponseEntity.java
> +			.reasonPhrase("OK");
다음 pr에서 반영하겠습니다

2023-03-01 12:08 UTC, rlatls1997 commented on src/main/java/webserver/ResponseEntity.java
> +	}
빌더에 [플루언트 API](https://medium.com/xebia-engineering/fluent-builder-pattern-with-a-real-world-example-7b61be375a40)형식을 적용해봤습니다. 

일반적인 빌더패턴은 값의 입력을 강제할 수 없지만(바로 build()메서드를 호출하면 되므로), 플루언트 빌더패턴에선 반환타입을 구한하는 인터페이스의 타입으로 명시하여 사용자로부터 입력을 강제할 수 있어서 좋더라구요.

내부에서 정적팩토리로 빈 빌더를 생성해서 반환해주다가 외부에서 직접 입력해주던 부분까지 내부로 가져오게 되었는데, 말씀하신대로 지금대로만 사용한다면 인터페이스까진 필요 없을 것 같네요. 

좀 보다보니.. 인터페이스를 외부에서 구현하면 플루언트빌더로 입력을 강제하는게 무용지물아닌가 하는 생각이 드네요. 이런 이유때문에 인터페이스를 private으로 해야하나 했는데 그럴거면 그냥 매개변수가 있는 생성자를 사용하는게 낫지 않나 하는 생각도 들고요.

이 부분은 좀 더 고민해보겠습니다.

2023-03-01 12:09 UTC, merged