CHAP3
ham-study/jwp pull request #9
Opened 2023-02-21 08:15 UTC by seung-hun-h

2023-02-23 15:21 UTC, rlatls1997 requested changes
보고 많이 배웠습니다. 
코드 보면서 퀄리티에 신경쓰지않고 구현에만 몰두했던게 창피해지네요.

수고하셨습니다.

2023-02-23 15:21 UTC, rlatls1997 commented on src/main/java/handler/UserHandler.java
> +		}
user정보가 없을 때 얼리리턴하면 불필요한 success초기화를 하지 않아도 돼서 더 깔끔하다고 생각했습니다.
```suggestion
		if (Objects.isNull(user)) {
		 	 HttpResponseHeader header = new HttpResponseHeader(HttpStatus.UNAUTHORIZED);
		 	 return new HttpResponse(header);
		}
		
		boolean success = user.login(params.get("password"));
```

2023-02-23 15:21 UTC, rlatls1997 commented on src/main/java/webserver/HttpContentType.java
> +			.orElse(APPLICATION_OCTET_STREAM.contentType);
운영중인 서비스라면 getContentType메서드가 자주 호출될 것 같은데 매번 enum value를 순회해야하는게 비효율적으로 보입니다. extension을 key로가진 map을 고려해볼만 한 것 같습니다.

2023-02-23 15:21 UTC, rlatls1997 commented on src/main/java/webserver/HttpRequestUri.java
> +	public static final String QUERY_STRING_SEPARATOR = "?";
다른데서 안보이는데 private 사용하는게 좋아보입니다.

2023-02-23 15:21 UTC, rlatls1997 commented on src/main/java/webserver/HttpRequestUri.java
> +		}
if 부정문이 잘 안보여서요.
부정문 없이 만들어도 됐을 것 같은데 이유가 있나요?

2023-02-23 15:21 UTC, rlatls1997 commented on src/main/java/webserver/HttpStatus.java
> +	private final String reason;
보통 reason이라고 하나요?
제 주관이지만 네이밍이 모호한 것 같습니다.

2023-02-24 08:12 UTC, seung-hun-h commented on src/main/java/handler/UserHandler.java
> +		}
플래그 변수를 사용하지 않아 더 깔끔해졌네요. 반영하겠습니다

2023-02-24 08:15 UTC, seung-hun-h commented on src/main/java/webserver/HttpRequestUri.java
> +		}
부정문을 사용하지 않으면 if문에 uri 파싱 로직이 들어가기 때문에 ealry return 하는 것이 좋다고 생각했습니다.
지금보니 잘 보이지 않을 수 있겠네요. 로직 수정하겠습니다

2023-02-24 08:18 UTC, seung-hun-h commented on src/main/java/webserver/HttpStatus.java
> +	private final String reason;
저도 이 변수에 대한 네이밍을 고민했었는데요. http/1.1에 나와있길래 사용했습니다.
https://www.ibm.com/docs/en/cics-ts/5.4?topic=concepts-status-codes-reason-phrases

2023-02-25 10:51 UTC, rlatls1997 commented on src/main/java/webserver/HttpStatus.java
> +	private final String reason;
reason이라고 하는지 몰랐네요. 전 reasonPhrase가 더 명확해서 좋은데 reason도 충분한 것 같습니다.

2023-02-26 13:17 UTC, rlatls1997 approved these changes

2023-02-26 13:18 UTC, rlatls1997 commented
변경사항 모두 확인했습니다.

2023-03-01 10:49 UTC, merged